"""Scheduled link-failure snapshots for dynamic topology experiments."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Sequence, Tuple

import networkx as nx
import numpy as np

from network.topology import NetworkGraph


@dataclass(frozen=True)
class LinkFailureEvent:
    """One scheduled edge removal and optional recovery."""

    edge: Tuple[int, int]
    start_time: float
    recovery_time: Optional[float] = None

    @property
    def end_time(self) -> Optional[float]:
        """Return the absolute recovery time, if the failure recovers."""
        if self.recovery_time is None:
            return None
        return self.start_time + self.recovery_time

    def active_at(self, t: float) -> bool:
        """Return True when this failure is active at time ``t``."""
        if t < self.start_time:
            return False
        if self.end_time is None:
            return True
        return t < self.end_time


class LinkFailureSchedule:
    """Adjacency snapshots generated by scheduled edge removals."""

    def __init__(
        self,
        base_adjacency: np.ndarray,
        events: Sequence[LinkFailureEvent],
        directed: bool = False,
    ) -> None:
        """Create a schedule from a base adjacency matrix and failure events."""
        adjacency = np.asarray(base_adjacency, dtype=float)
        if adjacency.ndim != 2 or adjacency.shape[0] != adjacency.shape[1]:
            raise ValueError("base_adjacency must be square")
        self.base_adjacency = adjacency.copy()
        self.events = list(events)
        self.directed = bool(directed)

    @classmethod
    def schedule_failures(
        cls,
        graph: NetworkGraph,
        T: float,
        dt: float,
        n_failures: Optional[int] = None,
        seed: int = 0,
        recovery_time: Optional[float] = None,
    ) -> "LinkFailureSchedule":
        """Schedule random edge failures for a ``NetworkGraph``."""
        if T <= 0.0:
            raise ValueError("T must be positive")
        if dt <= 0.0:
            raise ValueError("dt must be positive")
        if recovery_time is not None and recovery_time <= 0.0:
            raise ValueError("recovery_time must be positive when provided")

        nodelist = list(graph.graph.nodes())
        if not nodelist:
            raise ValueError("graph must contain at least one node")

        base_adjacency = nx.to_numpy_array(graph.graph, nodelist=nodelist, dtype=float)
        index_by_node = {node: idx for idx, node in enumerate(nodelist)}
        candidate_edges = [
            (index_by_node[u], index_by_node[v])
            for u, v in graph.graph.edges()
            if u in index_by_node and v in index_by_node
        ]
        if not candidate_edges:
            raise ValueError("graph must contain at least one edge")

        if n_failures is None:
            n_failures = max(1, int(np.ceil(T / 100.0)))
        if n_failures < 0:
            raise ValueError("n_failures must be non-negative")

        rng = np.random.default_rng(seed)
        replace = n_failures > len(candidate_edges)
        if n_failures == 0:
            selected_edges: list[Tuple[int, int]] = []
        else:
            edge_indices = rng.choice(len(candidate_edges), size=n_failures, replace=replace)
            selected_edges = [candidate_edges[int(idx)] for idx in np.atleast_1d(edge_indices)]

        start_low = min(dt, T)
        start_times = np.sort(rng.uniform(start_low, T, size=n_failures)) if n_failures else np.array([])
        events = [
            LinkFailureEvent(edge=edge, start_time=float(start), recovery_time=recovery_time)
            for edge, start in zip(selected_edges, start_times)
        ]
        return cls(
            base_adjacency=base_adjacency,
            events=events,
            directed=graph.graph.is_directed(),
        )

    def get_adjacency_at(self, t: float) -> np.ndarray:
        """Return the active adjacency matrix at simulation time ``t``."""
        adjacency = self.base_adjacency.copy()
        for event in self.events:
            if not event.active_at(t):
                continue
            u, v = event.edge
            adjacency[u, v] = 0.0
            if not self.directed:
                adjacency[v, u] = 0.0
        return adjacency

    def as_time_series(self, times: np.ndarray) -> np.ndarray:
        """Materialize adjacency snapshots with shape ``(n_steps, n, n)``."""
        time_values = np.asarray(times, dtype=float)
        if time_values.ndim != 1:
            raise ValueError("times must be a one-dimensional array")
        return np.stack([self.get_adjacency_at(float(t)) for t in time_values], axis=0)
